services:
  - type: web
    name: ownwrites-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Add other environment variables here
    healthCheckPath: /health
    plan: free
